---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service-ext
spec:
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  externalIPs:
    - 3.7.234.42
