---
apiVersion: v1
kind: Service
metadata:
  name: blue-svc
  namespace: blue
spec:
  selector:
    app: blue
  ports:
    - name: blue-svc
      protocol: TCP
      port: 80
      targetPort: 80
---
