---
apiVersion: v1
kind: Service
metadata:
  name: green-svc
  namespace: green
spec:
  selector:
    app: green
  ports:
    - name: green-svc
      protocol: TCP
      port: 80
      targetPort: 80
---
