---
apiVersion: v1
kind: Service
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: np-argocd
    namespace: argocd
  spec:
    ports:
    - nodePort: 30663
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app.kubernetes.io/name: argocd-server
    type: NodePort
  status:
    loadBalancer: {}
---
