---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
  namespace: blue
  labels:
    app: blue
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue
      version: v1
  template:
    metadata:
      labels:
        app: blue
        version: v1
    spec:
      containers:
      - name: blue
        image: docker.io/giriraj789/informatica:v1
        ports:
        - containerPort: 80
          name: http-v1
---
